version: "3.3"
services:
  # ursim:
  #   image: felixtechnikum/samy:ursim
  #   ports:
  #     - 6080:80
  #     - 30004:30004
  #     - 30002:30002
  #     - 30003:30003
  #     - 29999:29999
  core:
    image: felixtechnikum/samy:samy-core
    ports:
      - 4840:4840 
    volumes:
      - samy-conf:/usr/src/samy/configFiles
  ur5:
    image: felixtechnikum/samy:ur5-plugin
    command: python3 main.py core RobotUR5
    tty: true
    volumes:
      - samy-conf:/usr/src/samy/configFiles
  controller:
    image: felixtechnikum/samy:BPMNController
    command: python3 Tests/startBPMNController.py core Test_BPMN_no_parallel.diagram BPMNbasedController_Configuration_File.yaml
    tty: true
    volumes:
      - samy-conf:/usr/src/samy/configFiles

  config:
    image: felixtechnikum/samy:samy-config
    volumes:
      - samy-conf:/configFiles
    ports:
      - 8000:8000

volumes:
  samy-conf: