States:
  RobotUR5_Ready:
    key: 'Robot_RobotUR5_CurrentState'
    type: 'String'
    values:
     - Ready
  Start_Ready:
    key: Robot_RobotUR5_CurrentState
    type: String
    values:
    - Ready
